<?php
/**
 * Plugin Name:       Zinn® Chat
 * Plugin URI:        https://zinndigital.com/wordpress-plugins/zinn-chat
 * Description:       A fast, privacy-respecting live chat for your website. Answers visitors with AI when you are busy, hands them to you when they need a person, and emails you anything you miss. Under 10 KB on the page and no requests at all until somebody opens it.
 * Version:           1.1.2
 * Requires at least: 6.6
 * Requires PHP:      8.2
 * Author:            Neil Lock — CEO, Zinn Digital® Ltd
 * Author URI:        https://zinndigital.com
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       zinn-chat
 * Domain Path:       /languages
 * Update URI:        https://zinndigital.com
 *
 * @package ZinnChat
 *
 * ⚖️ **Owner, 2026-09-09:** *"what about building our own tawk.io style chat plugin and
 * backend as a stand alone product with premium features for wp and any site with js and
 * things? So we can install on all our customers wp sites by default and make it better
 * performance optimised and ai integrated and better than tawk's slow shitty expensive
 * one etc?"*
 *
 * ⛔⛔ **ACTIVE ONLY WHEN THE SITE OWNER SWITCHES IT ON.** It may be present on a site
 * whose owner has never asked for a chat widget — it is installable from wordpress.org and
 * from our own catalogue, and the deploy footprint is intended to carry it.
 * ⚠️ It does NOT carry it today: `engine/hosting/platform_plugin.py` ships exactly one
 * plugin, `zinn-cache` (measured 2026-09-12, D25514). The consent design below does not
 * depend on which is true, and must not be relaxed if the footprint ever widens. It does
 * NOTHING until a key is saved and the box is ticked: no script, no markup, no request,
 * no cookie, no storage. A chat window that starts talking to somebody's visitors unasked
 * is a consent problem, not a feature — and under the GDPR it would be our customer who
 * answered for it.
 *
 * ⭐ **The performance claim is the product, so it is structural rather than careful.**
 * The widget is enqueued with `defer`, in the footer, and carries its configuration
 * INLINE as a data attribute — so a page nobody chats on makes not one network request
 * on the widget's behalf. The settings are already in the database on the server that is
 * rendering the page; making the visitor's browser go and ask for them would be paying a
 * round trip for something we were holding all along.
 */

declare( strict_types = 1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'ZINN_CHAT_VERSION', '1.1.2' );
define( 'ZINN_CHAT_FILE', __FILE__ );
define( 'ZINN_CHAT_DIR', plugin_dir_path( __FILE__ ) );

// ⛔ `__DIR__`, not the `ZINN_CHAT_DIR` constant, and the difference is a GATE rather than
// taste. `scripts/wp-class-loader-check.py` reads these lines statically to prove every
// class the plugin CALLS is in a file it LOADS — a `require_once <CONSTANT> . '…'` is
// invisible to it, so it reported four classes as never loaded and a PHP fatal at each
// call. The constant was resolvable only at run time, which is exactly when a fatal is too
// late to be useful.
require_once __DIR__ . '/includes/class-zinn-chat-settings.php';
require_once __DIR__ . '/includes/class-zinn-chat-widget.php';
require_once __DIR__ . '/includes/class-zinn-chat-admin.php';
require_once __DIR__ . '/includes/class-zinn-chat-sync.php';
require_once __DIR__ . '/includes/class-zinn-chat-updater.php'; // Generated by wp/bin/build-updater.php.

/**
 * Boot the plugin.
 *
 * ⛔ Hooked on `plugins_loaded` rather than run at include time: every `add_action` below
 * needs WordPress to be up, and a plugin that does work while it is being included is one of
 * the things a directory reviewer looks for.
 *
 * ⛔⛔ **This docblock must stay true of BOTH build targets.** `wp/bin/build-plugin.php`
 * strips the textdomain call and the updater from the `--dotorg` zip, so prose here that
 * explains machinery the reviewer cannot find is a stale comment shipped to wordpress.org
 * — exactly the class `docs/432` §2a records for `readme.txt`. Anything specific to a
 * stripped call belongs on the call's own `//` lines, which the transform removes with it.
 */
function zinn_chat_boot(): void {
	// ⛔ The call needs WordPress up, which is the other half of the `plugins_loaded` hook
	// above. It is stripped from the `--dotorg` build: a plugin in the directory receives its
	// translations from translate.wordpress.org and WordPress has loaded them automatically
	// since 4.6, so calling it there is redundant and the directory's own checker flags it.
	// A plugin we distribute ourselves receives no language packs at all, so this call is what
	// makes the bundled `languages/` directory work and MUST stay in the default build.
	load_plugin_textdomain( 'zinn-chat', false, dirname( plugin_basename( ZINN_CHAT_FILE ) ) . '/languages' );

	Zinn_Chat_Widget::init();
	// ⛔ OUTSIDE the `is_admin()` branch below, and that is the whole point: the daily
	// refresh runs from WP-Cron, and a cron request is not an admin one. Registering it
	// with the settings screen would mean the cached config only ever updated while
	// somebody had wp-admin open — the defect `Zinn_Chat_Updater` already records as
	// D19745, one hook down.
	Zinn_Chat_Sync::init();

	// ⛔ Registered outside the `is_admin()` branch. WordPress runs its update check from
	// cron as well as from the updates screen, and a cron request is not an admin one — so
	// a plugin that only registers this in wp-admin is a plugin whose updates arrive when
	// somebody happens to look, rather than when they are published (D19745).
	( new Zinn_Chat_Updater( ZINN_CHAT_FILE, ZINN_CHAT_VERSION ) )->register();

	if ( is_admin() ) {
		Zinn_Chat_Admin::init();
	}
}
add_action( 'plugins_loaded', 'zinn_chat_boot' );

// The shared Zinn® panel in wp-admin — hosting, the marketplace, Zinn Hub® and this
// plugin's own guide (⚖️ owner, 2026-09-01). GENERATED by `wp/bin/build-promo.php`; do not
// edit the file it writes.
//
// ⛔ `require_once` rather than the autoloader, and a STRING callable rather than
// `array( Zinn_Chat_Promo::class, … )`. The class is deliberately global — it is shipped
// identically into every plugin, and some of them bootstrap inside a namespace where
// `::class` would resolve to a class that does not exist. A string callable resolves in
// the global namespace at call time, which is correct from all of them. `php -l` cannot
// see that mistake; only running it can.
require_once __DIR__ . '/includes/class-zinn-chat-promo.php';
add_action( 'plugins_loaded', array( 'Zinn_Chat_Promo', 'register' ) );

/**
 * Remove the options this plugin owns when it is deleted.
 *
 * ⭐ Registered here AND implemented in `uninstall.php`. WordPress calls the file for a
 * deletion from the plugins screen; the hook covers a programmatic `delete_plugins()`,
 * which is how our own fleet tooling removes it. Two entry points, one function, so they
 * cannot disagree about what "uninstalled" leaves behind.
 */
register_uninstall_hook( __FILE__, 'zinn_chat_uninstall' );

// ⛔ The daily config refresh is a scheduled event, so it is started and stopped with
// the plugin rather than left behind. A cron entry pointing at a hook nothing listens
// to is silent, permanent litter in every deactivated site's options table.
register_activation_hook( __FILE__, array( 'Zinn_Chat_Sync', 'schedule' ) );
register_deactivation_hook( __FILE__, array( 'Zinn_Chat_Sync', 'unschedule' ) );

/**
 * Delete every option this plugin created. Safe to call twice.
 */
function zinn_chat_uninstall(): void {
	delete_option( Zinn_Chat_Settings::OPTION );
	// ⭐ The scheduled event too. `register_deactivation_hook` normally gets there first,
	// but a plugin deleted from a site whose deactivation hook did not run (a file-level
	// removal by our own fleet tooling, say) would otherwise leave a cron entry firing at
	// a hook that no longer exists, for ever.
	if ( class_exists( 'Zinn_Chat_Sync' ) ) {
		Zinn_Chat_Sync::unschedule();
	}
}
