<?php
/**
 * The REST map: what every REST route of this plugin is to an AI agent (lane PLUGIN-MCP).
 *
 * GENERATED by wp/bin/mcp-rest-map.py from its curated table and the live route snapshot
 * wp/tests/wp-integration/mcp-routes.json. Edit the table, never this file: the unit suite
 * refuses a copy that differs, a route the table does not name, and a name with no route.
 *
 * @package ZinnDigital\ZinnChat
 */

declare( strict_types = 1 );

namespace ZinnDigital\ZinnChat\Mcp;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Every endpoint: an ability of its own (run through WordPress's REST dispatch by the kit's
 * Rest_Bridge), covered by a hand-written ability, or exempt with the reason.
 */
final class Rest_Map {

	/**
	 * The entries. Called on `wp_abilities_api_init`, when translations are loaded.
	 *
	 * @return array<int, array<string, string>>
	 */
	public static function entries(): array {
		return array(
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/assistant/ask',
				'name'        => 'zinn-chat/ask-assistant',
				'label'       => __( 'Ask the assistant', 'zinn-chat' ),
				'description' => __( 'Asks the site\'s AI assistant a question and returns its answer with every source it found.', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'GET',
				'route'       => '/zinn-chat/v1/agent/chat/{id}',
				'name'        => 'zinn-chat/get-chat',
				'label'       => __( 'Read a chat', 'zinn-chat' ),
				'description' => __( 'Returns one chat\'s messages and visitor details (after: only messages newer than this id).', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/chat/{id}/bot',
				'name'        => 'zinn-chat/hand-chat-to-assistant',
				'label'       => __( 'Hand a chat back to the assistant', 'zinn-chat' ),
				'description' => __( 'Returns a chat to the AI assistant, which answers the visitor from the site\'s content.', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/chat/{id}/close',
				'name'        => 'zinn-chat/close-chat',
				'label'       => __( 'Close a chat', 'zinn-chat' ),
				'description' => __( 'Ends a chat; the visitor can still ask for the transcript.', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/chat/{id}/reply',
				'name'        => 'zinn-chat/reply-chat',
				'label'       => __( 'Reply in a chat', 'zinn-chat' ),
				'description' => __( 'Sends a message to the visitor (text), or adds an internal note only agents see (note: true).', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/chat/{id}/take',
				'name'        => 'zinn-chat/take-chat',
				'label'       => __( 'Take a chat', 'zinn-chat' ),
				'description' => __( 'Assigns a waiting chat to the signed-in agent, so the visitor talks to a person.', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/chat/{id}/ticket',
				'name'        => 'zinn-chat/chat-to-ticket',
				'label'       => __( 'Turn a chat into a ticket', 'zinn-chat' ),
				'description' => __( 'Opens a ticket from a chat so it can be answered by email (needs the visitor\'s email address).', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/agent/chat/{id}/typing',
				'exempt' => 'a typing indicator: a person\'s keystrokes, not an action',
			),
			array(
				'method'      => 'GET',
				'route'       => '/zinn-chat/v1/agent/inbox',
				'name'        => 'zinn-chat/list-chats',
				'label'       => __( 'List live chats', 'zinn-chat' ),
				'description' => __( 'Lists the chats waiting, in progress and recently closed, with who is handling each.', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'GET',
				'route'       => '/zinn-chat/v1/agent/index',
				'name'        => 'zinn-chat/list-indexed-content',
				'label'       => __( 'List what the assistant knows', 'zinn-chat' ),
				'description' => __( 'Lists the content the assistant answers from, with its index status, a page at a time.', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/index/reembed',
				'name'        => 'zinn-chat/reembed-content',
				'label'       => __( 'Rebuild the assistant\'s search index', 'zinn-chat' ),
				'description' => __( 'Rebuilds the search vectors for one item (item_id) or everything (all: true) (managers only).', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/index/reindex',
				'name'        => 'zinn-chat/reindex-content',
				'label'       => __( 'Re-read content into the assistant', 'zinn-chat' ),
				'description' => __( 'Re-reads one item (item_id) or everything (all: true) into the assistant\'s index (managers only).', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/presence',
				'name'        => 'zinn-chat/set-presence',
				'label'       => __( 'Set your availability', 'zinn-chat' ),
				'description' => __( 'Marks the signed-in agent available or away for new chats (away: true or false).', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'GET',
				'route'       => '/zinn-chat/v1/agent/tickets',
				'name'        => 'zinn-chat/list-tickets',
				'label'       => __( 'List tickets', 'zinn-chat' ),
				'description' => __( 'Lists support tickets, filtered by status or a search, a page at a time.', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/tickets',
				'name'        => 'zinn-chat/create-ticket',
				'label'       => __( 'Open a ticket', 'zinn-chat' ),
				'description' => __( 'Opens a ticket on a customer\'s behalf (their email, a subject and the first message).', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'DELETE',
				'route'       => '/zinn-chat/v1/agent/tickets/{id}',
				'name'        => 'zinn-chat/delete-ticket',
				'label'       => __( 'Delete a ticket', 'zinn-chat' ),
				'description' => __( 'Deletes a ticket and its conversation for good (managers only).', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'GET',
				'route'       => '/zinn-chat/v1/agent/tickets/{id}',
				'name'        => 'zinn-chat/get-ticket',
				'label'       => __( 'Read a ticket', 'zinn-chat' ),
				'description' => __( 'Returns one ticket with its whole conversation, status, priority and assignee.', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/tickets/{id}/reply',
				'name'        => 'zinn-chat/answer-ticket',
				'label'       => __( 'Answer a ticket', 'zinn-chat' ),
				'description' => __( 'Replies to the customer by email (text), or adds an internal note (note: true); status optionally changes the ticket\'s status.', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/agent/tickets/{id}/update',
				'name'        => 'zinn-chat/update-ticket',
				'label'       => __( 'Change a ticket', 'zinn-chat' ),
				'description' => __( 'Changes a ticket\'s status, priority or assignee.', 'zinn-chat' ),
				'edition'     => 'free',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/chat/close',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/chat/human',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/chat/message',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/chat/poll',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/chat/rate',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/chat/status',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/chat/ticket',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/chat/transcript',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/chat/typing',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/kb/feedback',
				'exempt' => 'public visitor route: a reader\'s helpful / not helpful vote on an article',
			),
			array(
				'method' => 'GET,POST',
				'route'  => '/zinn-chat/v1/kb/search',
				'exempt' => 'public visitor route: the help widget\'s article search (agents use zinn-chat/search-kb)',
			),
			array(
				'method'      => 'GET',
				'route'       => '/zinn-chat/v1/pro/canned',
				'name'        => 'zinn-chat/list-canned-replies',
				'label'       => __( 'List saved replies (Pro)', 'zinn-chat' ),
				'description' => __( 'Lists the saved replies agents can insert, with their shortcuts.', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/pro/canned',
				'name'        => 'zinn-chat/save-canned-reply',
				'label'       => __( 'Save a saved reply (Pro)', 'zinn-chat' ),
				'description' => __( 'Creates or changes a saved reply (title, shortcut, body, department; id to change one).', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'DELETE',
				'route'       => '/zinn-chat/v1/pro/canned/{id}',
				'name'        => 'zinn-chat/delete-canned-reply',
				'label'       => __( 'Delete a saved reply (Pro)', 'zinn-chat' ),
				'description' => __( 'Deletes a saved reply.', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/pro/canned/{id}/use',
				'name'        => 'zinn-chat/fill-canned-reply',
				'label'       => __( 'Fill in a saved reply (Pro)', 'zinn-chat' ),
				'description' => __( 'Returns a saved reply\'s text with its placeholders filled for one chat or ticket.', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/pro/facts',
				'name'        => 'zinn-chat/set-conversation-details',
				'label'       => __( 'Set a conversation\'s department and tags (Pro)', 'zinn-chat' ),
				'description' => __( 'Sets the department and tags of a chat or ticket (kind: chat or ticket; id).', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'GET',
				'route'       => '/zinn-chat/v1/pro/gaps',
				'name'        => 'zinn-chat/list-kb-gaps',
				'label'       => __( 'List unanswered questions (Pro)', 'zinn-chat' ),
				'description' => __( 'Lists the questions visitors asked that the knowledge base could not answer.', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/pro/gaps/draft',
				'name'        => 'zinn-chat/draft-kb-from-gaps',
				'label'       => __( 'Draft help articles for unanswered questions (Pro)', 'zinn-chat' ),
				'description' => __( 'Writes draft knowledge-base articles answering the chosen questions (ids); they stay drafts.', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'edit_posts (the REST route\'s own check)',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/pro/gaps/status',
				'name'        => 'zinn-chat/set-kb-gap-status',
				'label'       => __( 'Mark unanswered questions (Pro)', 'zinn-chat' ),
				'description' => __( 'Marks unanswered questions as open, planned or dismissed (ids, status).', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/pro/inbound/{key}',
				'exempt' => 'the inbound-email webhook (authenticated by its secret key, called by the mail service)',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/pro/kb/draft',
				'name'        => 'zinn-chat/draft-kb-article',
				'label'       => __( 'Draft a help article from a ticket (Pro)', 'zinn-chat' ),
				'description' => __( 'Writes a draft knowledge-base article from a solved ticket; it stays a draft until a person publishes it.', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'edit_posts (the REST route\'s own check)',
			),
			array(
				'method'      => 'GET',
				'route'       => '/zinn-chat/v1/pro/kb/search',
				'name'        => 'zinn-chat/search-kb',
				'label'       => __( 'Search the knowledge base (Pro)', 'zinn-chat' ),
				'description' => __( 'Finds help articles to link in a reply (q: the search).', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/pro/push/subscribe',
				'exempt' => 'registers THIS browser for desktop notifications; an agent has no browser to register',
			),
			array(
				'method' => 'GET',
				'route'  => '/zinn-chat/v1/pro/push/summary',
				'exempt' => 'the service worker\'s notification text, read with the browser\'s own push token',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/pro/push/test',
				'exempt' => 'sends a test notification to THIS browser',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/pro/push/unsubscribe',
				'exempt' => 'removes THIS browser\'s desktop-notification subscription',
			),
			array(
				'method'      => 'GET',
				'route'       => '/zinn-chat/v1/pro/reports',
				'name'        => 'zinn-chat/get-stats',
				'label'       => __( 'Read support statistics (Pro)', 'zinn-chat' ),
				'description' => __( 'Returns chat and ticket numbers, response times and ratings for the last N days (days).', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/pro/suggest',
				'name'        => 'zinn-chat/suggest-reply',
				'label'       => __( 'Draft a reply with AI (Pro)', 'zinn-chat' ),
				'description' => __( 'Drafts a reply to a chat or ticket from the site\'s content; nothing is sent.', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method'      => 'POST',
				'route'       => '/zinn-chat/v1/pro/summary',
				'name'        => 'zinn-chat/summarise-conversation',
				'label'       => __( 'Summarise a conversation with AI (Pro)', 'zinn-chat' ),
				'description' => __( 'Summarises a chat or ticket in a few lines.', 'zinn-chat' ),
				'edition'     => 'pro',
				'capability'  => 'the REST route\'s own per-item permission check',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/pro/viewing',
				'exempt' => 'collision detection: which agent has a chat open in their browser right now',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/tickets',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/tickets/link',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/tickets/reply',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
			array(
				'method' => 'POST',
				'route'  => '/zinn-chat/v1/tickets/view',
				'exempt' => 'public visitor route: the chat widget or ticket form a visitor uses (token-scoped to their own conversation; an agent acting for a signed-in user has no business there)',
			),
		);
	}
}
