<?php
/**
 * Zinn Chat abilities: live chats, tickets, the assistant and (Pro) the help desk, for AI agents
 * (MCP) and REST.
 *
 * @package ZinnDigital\ZinnChat
 */

declare( strict_types = 1 );

namespace ZinnDigital\ZinnChat\Mcp;

use ZinnDigital\ZinnChat\Admin\Settings_Page;
use ZinnDigital\ZinnChat\Capabilities;
use ZinnDigital\ZinnChat\Conversations;
use ZinnDigital\ZinnChat\Plugin;
use ZinnDigital\ZinnChat\Rest;
use ZinnDigital\ZinnChat\Settings;
use ZinnDigital\ZinnChat\Tickets;
use ZinnDigital\ZinnChat\McpKit\Ability;
use ZinnDigital\ZinnChat\McpKit\Rest_Bridge;
use ZinnDigital\ZinnChat\McpKit\Server;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * The free abilities (owner, 2026-09-30: basic abilities free, bulk and AI in Pro).
 *
 * Every staff REST route of the plugin is an ability of its own (includes/mcp/class-rest-map.php,
 * generated by wp/bin/mcp-rest-map.py): reading and answering chats and tickets, the assistant and
 * its index, and in Pro the help desk (saved replies, AI drafts and summaries, the knowledge base,
 * unanswered questions, statistics). The visitor's own widget routes are never abilities.
 * Hand-written here: zinn-chat/get-overview (free), and in Pro zinn-chat/bulk-update-tickets and
 * zinn-chat/save-kb-article.
 */
final class Abilities {

	/** The ability category. */
	public const CATEGORY = 'zinn-chat';

	/**
	 * Boot the MCP kit for this plugin.
	 *
	 * @return void
	 */
	public static function boot(): void {
		Server::boot(
			array(
				'id'             => 'zinn-chat',
				'rest_namespace' => Rest::NS,
				'name'           => 'Zinn® Chat',
				'description'    => static function (): string {
					return __( 'Answer this site\'s live chats and support tickets with Zinn® Chat.', 'zinn-chat' );
				},
				'version'        => ZINN_CHAT_VERSION,
				'capability'     => Capabilities::ANSWER,
				'category'       => array(
					'slug'        => self::CATEGORY,
					'label'       => static function (): string {
						return __( 'Zinn® Chat', 'zinn-chat' );
					},
					'description' => static function (): string {
						return __( 'Live chats, support tickets, the AI assistant and the help desk.', 'zinn-chat' );
					},
				),
				'enabled'        => static function (): bool {
					return (bool) Settings::get( 'mcp', true );
				},
				'abilities'      => array( self::class, 'register' ),
				'vendor_dir'     => ZINN_CHAT_DIR . 'vendor/wordpress',
				'docs'           => array(
					'guide'      => 'https://zinndigital.com/wordpress-plugins/zinn-chat/mcp',
					'developers' => 'https://zinndigital.com/wordpress-plugins/zinn-chat/mcp-api',
				),
			)
		);
	}

	/**
	 * Register the abilities (on `wp_abilities_api_init`), then the Pro ones when licensed.
	 *
	 * @return void
	 */
	public static function register(): void {
		Ability::register(
			'zinn-chat/get-overview',
			array(
				'edition'             => 'free',
				'capability'          => Capabilities::ANSWER,
				'label'               => __( 'Read the support overview', 'zinn-chat' ),
				'description'         => __( 'Returns how many tickets are in each status and how many chats are waiting for a person (and their unread messages), and whether the chat, the assistant and tickets are switched on.', 'zinn-chat' ),
				'category'            => self::CATEGORY,
				'input_schema'        => array(
					'type'                 => 'object',
					'properties'           => array(),
					'additionalProperties' => false,
				),
				'output_schema'       => array(
					'type'       => 'object',
					'properties' => array(
						'tickets'  => array( 'type' => 'object' ),
						'chats'    => array( 'type' => 'object' ),
						'switches' => array( 'type' => 'object' ),
						'pro'      => array( 'type' => 'boolean' ),
					),
				),
				'execute_callback'    => array( self::class, 'overview' ),
				'permission_callback' => static function (): bool {
					return Capabilities::can_answer();
				},
				'annotations'         => array(
					'readonly'   => true,
					'idempotent' => true,
				),
			)
		);

		Ability::register(
			'zinn-chat/get-settings',
			array(
				'edition'             => 'free',
				'capability'          => Capabilities::MANAGE,
				'label'               => __( 'Read the chat settings', 'zinn-chat' ),
				'description'         => __( 'Returns every chat setting: the widget, the assistant, people and opening hours, tickets and email, the site index, privacy and spam.', 'zinn-chat' ),
				'category'            => self::CATEGORY,
				'input_schema'        => array(
					'type'                 => 'object',
					'properties'           => array(),
					'additionalProperties' => false,
				),
				'output_schema'       => array( 'type' => 'object' ),
				'execute_callback'    => array( self::class, 'settings' ),
				'permission_callback' => static function (): bool {
					return Capabilities::can_manage();
				},
				'annotations'         => array(
					'readonly'   => true,
					'idempotent' => true,
				),
			)
		);

		Ability::register(
			'zinn-chat/update-settings',
			array(
				'edition'             => 'free',
				'capability'          => Capabilities::MANAGE,
				'label'               => __( 'Change the chat settings', 'zinn-chat' ),
				'description'         => __( 'Changes the settings you send (settings: key to value) and keeps the rest. Each value is checked exactly as on the settings screen; get-settings lists the keys.', 'zinn-chat' ),
				'category'            => self::CATEGORY,
				'input_schema'        => array(
					'type'                 => 'object',
					'properties'           => array(
						'settings' => array(
							'type'          => 'object',
							'minProperties' => 1,
						),
					),
					'required'             => array( 'settings' ),
					'additionalProperties' => false,
				),
				'output_schema'       => array( 'type' => 'object' ),
				'execute_callback'    => array( self::class, 'update_settings' ),
				'permission_callback' => static function (): bool {
					return Capabilities::can_manage();
				},
				'annotations'         => array(
					'destructive' => true,
					'idempotent'  => true,
				),
			)
		);

		// Every other staff REST route of the plugin, as an ability of its own.
		require_once __DIR__ . '/class-rest-map.php';
		Rest_Bridge::register( Rest_Map::entries(), self::CATEGORY );

		// ⛔ The premium abilities load only when their file ships AND the licence allows it; the
		// directory name is split so the free package never carries the premium token.
		$pro = __DIR__ . '/pro_' . '_premium_only/class-pro-abilities.php'; // phpcs:ignore Generic.Strings.UnnecessaryStringConcat.Found -- deliberate split, see above.
		if ( is_readable( $pro ) && Plugin::is_pro() ) {
			require_once $pro;
			Pro\Pro_Abilities::register();
		}
	}

	/**
	 * Zinn-chat/get-overview.
	 *
	 * @return array<string, mixed>
	 */
	public static function overview(): array {
		return array(
			'tickets'  => Tickets::counts(),
			'chats'    => Conversations::counts(),
			'switches' => array(
				'chat'      => (bool) Settings::get( 'enabled', false ),
				'assistant' => (bool) Settings::get( 'ai_enabled', true ),
				'people'    => (bool) Settings::get( 'human_enabled', true ),
				'tickets'   => (bool) Settings::get( 'tickets_enabled', true ),
			),
			'pro'      => Plugin::is_pro(),
		);
	}

	/**
	 * Zinn-chat/get-settings (the site owner's MCP switch is the screen's, so it is not offered).
	 *
	 * @return array<string, mixed>
	 */
	public static function settings(): array {
		$all = Settings::all();
		unset( $all['mcp'], $all['schema'] );

		return $all;
	}

	/**
	 * Zinn-chat/update-settings, through Settings::save(), the screen's own sanitiser.
	 *
	 * @param array<string, mixed> $input Input.
	 * @return array<string, mixed>|\WP_Error
	 */
	public static function update_settings( array $input ) {
		$changes = (array) $input['settings'];
		// Every key the screen offers: the defaults, and each tab's fields (Pro adds its own there).
		$known = Settings::defaults();
		if ( class_exists( Settings_Page::class ) ) {
			foreach ( array_keys( Settings_Page::tabs() ) as $tab ) {
				$known += Settings_Page::fields( (string) $tab );
			}
		}
		foreach ( array_keys( $changes ) as $key ) {
			if ( ! array_key_exists( (string) $key, $known ) || in_array( $key, array( 'mcp', 'schema' ), true ) ) {
				/* translators: %s: a settings key. */
				return new \WP_Error( 'zinn_chat_unknown_setting', sprintf( __( 'There is no chat setting called %s that can be changed here.', 'zinn-chat' ), (string) $key ), array( 'status' => 400 ) );
			}
		}
		Settings::save( $changes );

		return self::settings();
	}

	/**
	 * The settings tab's MCP details, below its form (the switch is the tab's own field).
	 *
	 * @return void
	 */
	public static function panel(): void {
		Server::render_panel();
	}
}
