<?php
/**
 * Loads every part of Zinn® Chat and starts it.
 *
 * ⛔ Explicit `require_once __DIR__ . '…'` lines, never an autoloader or a constant-built path:
 * `scripts/wp-class-loader-check.py` reads these lines statically to prove that every class the
 * plugin calls is in a file it loads, and a path built at run time is invisible to it.
 *
 * @package ZinnDigital\ZinnChat
 */

declare( strict_types = 1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Action Scheduler (the background queue WooCommerce uses). Its own loader picks the newest copy
// any active plugin bundles, so ours coexists with WooCommerce's.
require_once dirname( __DIR__ ) . '/vendor/woocommerce/action-scheduler/action-scheduler.php';
require_once __DIR__ . '/ai-core/load.php';

require_once __DIR__ . '/class-settings.php';
require_once __DIR__ . '/class-capabilities.php';
require_once __DIR__ . '/class-schema.php';
require_once __DIR__ . '/class-util.php';
require_once __DIR__ . '/class-spam.php';
require_once __DIR__ . '/class-conversations.php';
require_once __DIR__ . '/class-tickets.php';
require_once __DIR__ . '/class-mailer.php';
require_once __DIR__ . '/class-presence.php';
require_once __DIR__ . '/index/class-vectors.php';
require_once __DIR__ . '/index/class-chunker.php';
require_once __DIR__ . '/index/class-html-text.php';
require_once __DIR__ . '/index/class-extractor.php';
require_once __DIR__ . '/index/class-index.php';
require_once __DIR__ . '/index/class-search.php';
require_once __DIR__ . '/index/class-queue.php';
require_once __DIR__ . '/class-assistant.php';
require_once __DIR__ . '/class-woo.php';
require_once __DIR__ . '/class-privacy.php';
require_once __DIR__ . '/class-rest.php';
require_once __DIR__ . '/class-agent-rest.php';
require_once __DIR__ . '/class-widget.php';
require_once __DIR__ . '/class-connect.php';
require_once __DIR__ . '/class-front-tickets.php';
require_once __DIR__ . '/class-blocks.php';
require_once __DIR__ . '/class-plugin.php';
require_once __DIR__ . '/admin/class-admin.php';
require_once __DIR__ . '/admin/class-settings-page.php';
require_once __DIR__ . '/admin/class-console-page.php';
require_once __DIR__ . '/admin/class-tickets-page.php';
require_once __DIR__ . '/admin/class-assistant-page.php';
require_once __DIR__ . '/admin/class-setup-page.php';
require_once __DIR__ . '/admin/class-upsell.php';
require_once __DIR__ . '/class-freemius-i18n.php';
// Generated by wp/bin/build-updater.php; the WordPress.org build removes this line and the file.
require_once __DIR__ . '/class-zinn-chat-updater.php';
// The shared Zinn® panel in wp-admin. GENERATED by wp/bin/build-promo.php.
require_once __DIR__ . '/class-zinn-chat-promo.php';

\ZinnDigital\ZinnChat\AiCore\Core::boot(
	array(
		'slug' => 'zinn-chat',
		'name' => 'Zinn® Chat',
		'pro'  => static function (): bool {
			return \ZinnDigital\ZinnChat\Plugin::is_pro();
		},
	)
);

\ZinnDigital\ZinnChat\Plugin::init();
add_action( 'plugins_loaded', array( 'Zinn_Chat_Promo', 'register' ) );

register_activation_hook( ZINN_CHAT_FILE, array( '\ZinnDigital\ZinnChat\Plugin', 'activate' ) );
register_deactivation_hook( ZINN_CHAT_FILE, array( '\ZinnDigital\ZinnChat\Plugin', 'deactivate' ) );

if ( ! function_exists( 'zinn_chat_uninstall' ) ) {
	/**
	 * Delete everything this plugin stored, when the owner deletes it and chose to remove data.
	 * Called by the licensing SDK's `after_uninstall` action (it refuses a root uninstall.php).
	 *
	 * @return void
	 */
	function zinn_chat_uninstall(): void {
		\ZinnDigital\ZinnChat\Plugin::uninstall();
	}
}
